### ISSUE TITLE
Error instaling current version

### ISSUE THREAD

**Issue by jhoanir** [featherbear/presonus-studiolive-api-midi-integration#5]
➜  presonus-studiolive-api-midi-integration git:(master) yarn install               
yarn install v1.22.19
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/5] ⠂ dtrace-provider
[2/5] ⠂ midi
[5/5] ⠂ presonus-studiolive-api-simple-api
[-/5] ⠂ waiting...
error /Users/jhoanir/Documents/presonus-studiolive-api-midi-integration/node_modules/presonus-studiolive-api-simple-api: Command failed.
Exit code: 2
Command: npm run --silent transpile
Arguments: 
Directory: /Users/jhoanir/Documents/presonus-studiolive-api-midi-integration/node_modules/presonus-studiolive-api-simple-api
Output:
src/index.ts(3,42): error TS2724: '"presonus-studiolive-api"' has no exported member named 'CHANNELTYPES'. Did you mean 'ChannelTypes'?
src/index.ts(3,56): error TS2614: Module '"presonus-studiolive-api"' has no exported member 'MESSAGETYPES'. Did you mean to use 'import MESSAGETYPES from "presonus-studiolive-api"' instead?
src/index.ts(26,9): error TS2322: Type 'string | number | symbol' is not assignable to type '"LINE" | "MAIN" | "TALKBACK" | "AUX" | "SUB" | "FX" | "FXRETURN" | "RETURN"'.

**Comment by featherbear** [comment]
This was due to version inconsistencies, as I did not update the dependencies. 
You can try 66499321e4bb5e1e8e27424513325905a2d780d4

I'm going to be changing some fundamental things to better allow multiple devices, so I'll close this issue as stale
